### ISSUE TITLE
Add a character in countdown

### ISSUE THREAD

**Issue by Galixte** [dmzx/countdown#17]
Hi @dmzx,

in countdown how to add a character `0` before 1, 2, 3, 4 … until 9 but not for 10, 11 etc… ?

Like that: 01, 02, 03, 04… until 09.

I think the solution is to edit this file: https://github.com/dmzx/countdown/blob/master/styles/prosilver/template/jquery.jcountdown.min.js, but i don’t know what part of code i have to modify.

**Comment by dmzx** [comment]
https://github.com/dmzx/countdown/blob/master/styles/prosilver/template/event/overall_footer_after.html#L12 

set to true

**Comment by Galixte** [comment]
Thanks a lot to you !
