### ISSUE TITLE
Timezone on = no countdown

### ISSUE THREAD

**Issue by Galixte** [dmzx/countdown#7]
Hi,

when i active this option:

```
Enable timezone:
Enable or disable the Ptimezone here
```

The countdown is not displayed.

Also i don't understand what the form of text/number that i have to enter in the next field:

```
Timezone settings:
If you want to use a specific timezone for all users you can type it here.
Like "-6" for Central Standard Time and "4" for Gulf Standard Time
```

**Comment by dmzx** [comment]
Update version 1.0.3 
enable timezon and fill in timezone default in timezone settings

**Comment by Galixte** [comment]
It's OK, thanks !
